version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./index.php:/var/www/html/index.php
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
