version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: sql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    container_name: sql_web
    ports:
      - "8085:80"
    depends_on:
      - db

volumes:
  db_data:
